// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU2bCfSWE8fnful9tYlihAdcDumA4KqDs',
    appId: '1:471663152445:web:3b810e035f2657d2310954',
    messagingSenderId: '471663152445',
    projectId: 'library-management-syste-4094b',
    authDomain: 'library-management-syste-4094b.firebaseapp.com',
    storageBucket: 'library-management-syste-4094b.firebasestorage.app',
    measurementId: 'G-W6WSW8TYZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ-2uMOmg_DoWehUabDOaERE8HRV7ob1I',
    appId: '1:471663152445:android:a67ce52d3269f2bf310954',
    messagingSenderId: '471663152445',
    projectId: 'library-management-syste-4094b',
    storageBucket: 'library-management-syste-4094b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-r6HZeZ0STyXSCJyVdHRTaXBBHGi0ww',
    appId: '1:471663152445:ios:8d6e19a5d1b7a726310954',
    messagingSenderId: '471663152445',
    projectId: 'library-management-syste-4094b',
    storageBucket: 'library-management-syste-4094b.firebasestorage.app',
    iosClientId: '471663152445-hunheij78hjq5lmarb00ibpt0ksbrilf.apps.googleusercontent.com',
    iosBundleId: 'com.example.problemsheet1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-r6HZeZ0STyXSCJyVdHRTaXBBHGi0ww',
    appId: '1:471663152445:ios:8d6e19a5d1b7a726310954',
    messagingSenderId: '471663152445',
    projectId: 'library-management-syste-4094b',
    storageBucket: 'library-management-syste-4094b.firebasestorage.app',
    iosClientId: '471663152445-hunheij78hjq5lmarb00ibpt0ksbrilf.apps.googleusercontent.com',
    iosBundleId: 'com.example.problemsheet1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU2bCfSWE8fnful9tYlihAdcDumA4KqDs',
    appId: '1:471663152445:web:e853d3982c6a5a9d310954',
    messagingSenderId: '471663152445',
    projectId: 'library-management-syste-4094b',
    authDomain: 'library-management-syste-4094b.firebaseapp.com',
    storageBucket: 'library-management-syste-4094b.firebasestorage.app',
    measurementId: 'G-CR3CNWHRTN',
  );
}
